=== CheeseMite/web-technologies/pr8/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="book">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="page" maxOccurs="unbounded" >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="colontitul">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="theme_r" maxOccurs="1" minOccurs="0"/>
                    <xs:element type="xs:string" name="nump_l" maxOccurs="1" minOccurs="0"/>
                    <xs:element type="xs:string" name="theme_l" maxOccurs="1" minOccurs="0"/>
                    <xs:element type="xs:string" name="nump_r" maxOccurs="1" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="content">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="image" minOccurs="0" maxOccurs="unbounded" />
                    <xs:element type="xs:string" name="image_title" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="p" maxOccurs="unbounded" minOccurs="0" >
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="b" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="num" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:byte" name="size"/>
      <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CheeseMite/web-technologies/pr8/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE book >

<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd"  size="2" name="somebook" >
    <page num="1">
        <colontitul>
            <theme_r>Тема 1</theme_r>
            <nump_l>8</nump_l>
        </colontitul>
        <content>
        <image/>
        <image_title>Рисунок 1.1. Объединение сетей в Интернет</image_title>
        <p><b>Веб-страница</b> – гипертекстовой ресурс Всемирной паутины, обычно напи-
        санный на языке HTML. Веб-страница может содержать ссылки для перехода
        
        на другие страницы, а также изображения, медиафайлы, например звуковые
        файлы и видео, Flash-анимацию и т.п.
        
        Программа, демонстрирующая веб-страницу, называется веб-браузер. Не-
        сколько веб-страниц, объединенных общей темой и дизайном, образуют веб-
        сайт.
        </p>
        <p>
        <b>Веб-сервер (HTTP-сервер)</b> – это программное обеспечение (ПО), предостав-
        ляющее доступ к сайтам. Наиболее популярными веб-серверами являются
        
        Apache (для ОС Windows и Unix) и Microsoft IIS (для Windows). Также веб-
        сервером называют компьютер, на котором установлено такое ПО.
        </p>
        <p>
            
        URL (Uniform Resource Locator) – адрес ресурса.
        Структура URL:
        протокол :// пользователь : пароль @ хост : порт / путь ? запрос
        </p>
    </content>
    </page>    
    <page num="2">
        <colontitul>
            <theme_l>Содержание</theme_l>
            <nump_r>9</nump_r>
        </colontitul>
        <content>
            <p>
            Некоторые элементы URL могут быть опущены. Чаще всего адрес имеет вид
            протокол :// хост / путь, </p>
            <p>
            где протокол – http, https, ftp, skype и др.
            хост – доменное имя (или IP-адрес)
            путь – местонахождение ресурса на хосте
            </p>
            <p>Например: http://www.redut.ru/forum/index.php
            При помощи URL можно ссылаться на любой открытый ресурс, будь то
            страница, изображение, файл для загрузки и т.д.
            Для обращения к сайту используют доменное имя. Доменное имя состоит из
            нескольких доменов, разделенных точкой.
            </p>
            <p>
            Например:
            maps.google.com – означает, что домен третьего уровня maps входит в домен
            второго уровня google, который в свою очередь входит в домен первого
            (верхнего) уровня com.
            Домены верхнего уровня делятся на общие и географические. Общие домены
            предназначены для определенного класса организаций, например:
            .com – для коммерческих сайтов;
            .org – для некоммерческих организаций;
            .net – для сайтов, чья деятельность связана с Интернетом.
            Географические домены выделяются для конкретной страны, например:
            .ru – Россия;
            .us – США
            .eu – Европейский союз
            .de – Германия
            </p>
            <p>
            Использование географического домена не всегда означает то, что сайт раз-
            мещается в соответствующей стране или имеет к ней какое-либо отношение.
            
            Например, многие телекомпании используют домен .tv островного государ-
            ства Тувалу.
            </p>
            <p>
            Помимо доменного имени для работы сайта необходим круглосуточно рабо-
            тающий веб-сервер, способный выдержать большие нагрузки. Услуга разме-
            щения веб-сайта на веб-сервере называется хостингом. Хостинг может быть
            
            платным или бесплатным. На платном хостинге, как правило, предоставляет-
            ся доменное имя второго уровня. За пользование хостингом и доменом взи-
            </p>
        </content>
    </page>
</book>
